canvas = document.getElementById("myCanvas");
ctx = canvas.getContext("2d");
color = "blue";
ctx.beginPath();
ctx.strokeStyle = color;
ctx.lineWidth = 6;
ctx.arc(300, 200, 40, 0, 2 * Math.PI);
ctx.stroke();
canvas = document.getElementById("myCanvas");
ctx = canvas.getContext("2d");
color = "orange";
ctx.beginPath();
ctx.strokeStyle = color;
ctx.lineWidth = 6;
ctx.arc(350, 230, 40, 0, 2 * Math.PI);
ctx.stroke();
canvas = document.getElementById("myCanvas");
ctx = canvas.getContext("2d");
color = "black";
ctx.beginPath();
ctx.strokeStyle = color;
ctx.lineWidth = 6;
ctx.arc(400, 200, 40, 0, 2 * Math.PI);
ctx.stroke();
canvas = document.getElementById("myCanvas");
ctx = canvas.getContext("2d");
color = "green";
ctx.beginPath();
ctx.strokeStyle = color;
ctx.lineWidth = 6;
ctx.arc(450, 230, 40, 0, 2 * Math.PI);
ctx.stroke();
canvas = document.getElementById("myCanvas");
ctx = canvas.getContext("2d");
color = "red";
ctx.beginPath();
ctx.strokeStyle = color;
ctx.lineWidth = 6;
ctx.arc(500, 200, 40, 0, 2 * Math.PI);
ctx.stroke();

